### ISSUE TITLE
Appearance properties settings work on Windows only

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#282]
I select a component in the AADL diagram and want to set appearance properties. The drop down menus work. There are three additional buttons (BTW, should the buttons have tooltips?), and when I click on either one of them I get the exception below. This works on Windows but not on Linux (tested with Ubuntu 16.04 and Kubuntu 17.10). Will test on Mac later today.
```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.eclipse.swt.graphics.ImageData.blit(ImageData.java:2940)
	at org.eclipse.swt.graphics.Image.init(Image.java:1681)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:822)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:291)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:240)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:218)
	at org.osate.ge.internal.ui.properties.AppearancePropertySection$ColorSelectionListener.createColorButton(AppearancePropertySection.java:340)
	at org.osate.ge.internal.ui.properties.AppearancePropertySection$ColorSelectionListener.widgetSelected(AppearancePropertySection.java:354)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by joeseibel** [comment]
Exception happens on macOS also.

**Comment by philip-alldredge** [comment]
@joeseibel Can you test the fix on macOS?
